# Generated by Django 4.2.1 on 2023-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_profile_address_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Телефон подтверждён'),
        ),
    ]
