# Generated by Django 4.2.1 on 2023-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='is_admin_reply',
            field=models.BooleanField(default=False, verbose_name='Ответ Админа'),
        ),
    ]
