# Generated by Django 4.2.1 on 2023-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ключ сессии'),
        ),
    ]
