# Generated by Django 4.2.1 on 2023-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_productinorder_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Сумма'),
        ),
    ]
